image: golang:1.13-alpine

variables:
  GORELEASER_IMAGE: goreleaser/goreleaser:latest
  NANCY_VERSION: v0.0.36

stages:
  - test
  - lint
  - check
  - snapshot

before_script:
  - apk --update add
    curl docker-cli file-dev gcc git libmagic musl-dev
    || echo ":D"

go test:
  stage: test
  script:
    - go test -v
      -cover -covermode atomic

eclint:
  stage: lint
  script:
    - go build -o eclint cmd/eclint/main.go
    - ./eclint -exclude "testdata/**/*"

golangci-lint:
  stage: lint
  image: golangci/golangci-lint
  script:
    - golangci-lint run -v

nancy:
  stage: check
  script:
    - curl -sL -o nancy
      "https://github.com/sonatype-nexus-community/nancy/releases/download/${NANCY_VERSION}/nancy-linux.amd64-${NANCY_VERSION}"
    - chmod +x nancy
    - ./nancy go.sum

go-mod-outdated:
  stage: check
  script:
    - go get -u github.com/psampaz/go-mod-outdated
    - go list -u -m -json all | $GOPATH/bin/go-mod-outdated -update -direct -ci

goreleaser snapshot:
  stage: snapshot
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
    - bin/goreleaser
      --snapshot --skip-sign
