image: golang:1.16-buster

variables:
  NANCY_VERSION: v1.0
  GIT_DEPTH: "0"

stages:
  - test
  - lint
  - check
  - snapshot

go test:
  stage: test
  script:
    - go test -v ./...
    - go test -v ./...
      -cover -covermode atomic
      -coverprofile coverage.out
      -json > test-report.json
    - go tool cover -func coverage.out
    - go list -u -m -json all > go-list.json
  artifacts:
    paths:
      - coverage.out
      - test-report.json
      - go-list.json

eclint:
  stage: lint
  script:
    - go build -o eclint gitlab.com/greut/eclint/cmd/eclint
    - ./eclint -exclude "testdata/**/*"

golangci-lint:
  stage: lint
  image: golangci/golangci-lint
  script:
    - golangci-lint run ./...
    - golangci-lint run -v ./...
      --issues-exit-code 0
      --out-format checkstyle > report.xml
  artifacts:
    paths:
      - report.xml

nancy:
  stage: check
  image: sonatypecommunity/nancy:${NANCY_VERSION}-alpine
  needs:
    - go test
  script:
    - cat go-list.json | nancy --quiet

sonarcloud check:
  stage: check
  allow_failure: true
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  needs:
    - go test
    - golangci-lint
  script:
    - sonar-scanner
      -Dsonar.projectVersion=$(git describe --abbrev=0 --tags)
      -Dsonar.qualitygate.wait=true  # this does nothing yet

go-mod-outdated:
  stage: check
  allow_failure: true
  needs:
    - go test
  script:
    - go get -u github.com/psampaz/go-mod-outdated
    - cat go-list.json | $GOPATH/bin/go-mod-outdated -update -direct -ci

goreleaser snapshot:
  stage: check
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - apt-get update -y
    - apt-get install -qy docker.io
    - curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
    - bin/goreleaser
      --snapshot --skip-sign
