image: golang:1.13

variables:
  GORELEASER_IMAGE: goreleaser/goreleaser:latest

stages:
  - test
  - lint
  - snapshot

go test:
  stage: test
  script:
    - go test -v
      -cover -covermode atomic
    - go build .
  artifacts:
    paths:
      - eclint

eclint:
  stage: lint
  script:
    - ./eclint -exclude "{lint_test.go,testdata/**/*}"

golangci-lint:
  stage: lint
  image: golangci/golangci-lint
  script:
    - golangci-lint run -v

goreleaser snapshot:
  stage: snapshot
  image: docker:stable
  services:
  - docker:dind
  script:
    - docker run
      --pull
      --rm
      --privileged
      -v /var/run/docker.sock:/var/run/docker.sock
      -v $PWD:/go/src/gitlab.com/$CI_PROJECT_PATH
      -w /go/src/gitlab.com/$CI_PROJECT_PATH
      $GORELEASER_IMAGE
      snapshot
