linters-settings:
  golint:
    min-confidence: 0.3
  gocyclo:
    min-complexity: 30

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofumpt
    - golint
    - gosec
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - megacheck
    - misspell
    - nakedret
    - nlreturn
    - nolintlint
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
    - whitespace
  disable-all: true
