linters-settings:
  golint:
    min-confidence: 0.3
  gocyclo:
    min-complexity: 28

linters:
  enable:
    - deadcode
    - dupl
    - errcheck
    - gocritic
    - gocyclo
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - megacheck
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - unused
    - varcheck
    - gosec
  disable-all: true
