linters-settings:
  golint:
    min-confidence: 0.3
  gocyclo:
    min-complexity: 28

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goimports
    - golint
    - gosec
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - megacheck
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
    - whitespace
    - wsl
  disable-all: true
