linters-settings:
  cyclop:
    max-complexity: 15
    package-average: 10
  golint:
    min-confidence: 0.3
  gocyclo:
    min-complexity: 30

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - golint
    - gomnd
    - ifshort
    - interfacer
    - maligned
    - scopelint
    - varnamelen
  fast: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goerr113
        - ifshort
        - paralleltest
        - testpackage
        - tparallel
    - path: main.go
      linters:
        - cyclop
        - wrapcheck
