linters-settings:
  cyclop:
    max-complexity: 15
    package-average: 10
  golint:
    min-confidence: 0.3
  gocyclo:
    min-complexity: 30

linters:
  disable:
    - exhaustivestruct
    - golint
    - gomnd
    - interfacer
    - maligned
    - scopelint
    - varnamelen
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused
  fast: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
        - ifshort
        - paralleltest
        - testpackage
        - tparallel
    - path: main.go
      linters:
        - cyclop
        - wrapcheck
