project_name: eclint

before:
  hooks:
  - go mod tidy
builds:
- id: eclint
  binary: eclint
  main: cmd/eclint/main.go
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
archives:
- replacements:
    386: i386
    amd64: x86_64
dockers:
- image_templates:
  - greut/eclint:latest
  - greut/eclint:{{ .Tag }}
  - greut/eclint:v{{ .Major }}
  - greut/eclint:v{{ .Major }}.{{ .Minor }}
  - registry.gitlab.com/greut/eclint:latest
  - registry.gitlab.com/greut/eclint:{{ .Tag }}
  - registry.gitlab.com/greut/eclint:v{{ .Major }}
  - registry.gitlab.com/greut/eclint:v{{ .Major }}.{{ .Minor }}
  - docker.pkg.github.com/greut/eclint/cmd:latest
  - docker.pkg.github.com/greut/eclint/cmd:{{ .Tag }}
  - docker.pkg.github.com/greut/eclint/cmd:v{{ .Major }}
  - docker.pkg.github.com/greut/eclint/cmd:v{{ .Major }}.{{ .Minor }}
  goos: linux
  goarch: amd64
  binaries:
  - eclint
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
checksum:
  name_template: 'checksums.txt'
signs:
- artifacts: checksum
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  gitlab:
    owner: greut
    name: eclint
