before:
  hooks:
    - go mod tidy
builds:
- id: eclint
  env:
  - CGO_ENABLED=0
archives:
- replacements:
    386: i386
    amd64: x86_64
dockers:
  - binaries:
    - eclint
    image_templates:
    - greut/eclint:latest
    - greut/eclint:{{ .Tag }}
    - greut/eclint:{{ .Tag }}
    - greut/eclint:v{{ .Major }}
checksum:
  name_template: 'checksums.txt'
signs:
  - artifacts: checksum
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  gitlab:
    owner: greut
    name: eclint
