project_name: eclint

before:
  hooks:
  - go mod tidy
builds:
- id: eclint
  binary: eclint
  main: ./cmd/eclint/main.go
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
archives:
- replacements:
    386: i386
    amd64: x86_64
dockers:
- image_templates:
  - greut/eclint:latest
  - greut/eclint:{{ .Tag }}
  - greut/eclint:v{{ .Major }}
  - registry.gitlab.com/greut/eclint:latest
  - registry.gitlab.com/greut/eclint:{{ .Tag }}
  - registry.gitlab.com/greut/eclint:v{{ .Major }}
  goos: linux
  goarch: amd64
  binaries:
  - eclint
checksum:
  name_template: 'checksums.txt'
signs:
- artifacts: checksum
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  gitlab:
    owner: greut
    name: eclint
